### ISSUE TITLE
OpenVPN blocks me from logging into flood

### ISSUE THREAD

**Issue by vleeuwenmenno** [h1f0x/rtorrent-flood-openvpn#3]
Hi,

I've been trying this thing but I am stuck.
I setup the conf so it connects to my VPN provider and it works because I see in the IP txt file the IP is different from my home IP.

Also in the openvpn log I see it succesfully connects.
But once it is connected to the vpn I cant access flood anymore.

What do I do?

**Comment by h1f0x** [comment]
Hi, 

Sorry for my very late response! :)

Actually that should not happen. I ran the same configuration obviously and the webUI of flood is reachable by the port as described. 

So.. how do you connect to it, when you have no openvpn connection?

Cheers

**Comment by h1f0x** [comment]
> Hi,
> 
> I've been trying this thing but I am stuck.
> I setup the conf so it connects to my VPN provider and it works because I see in the IP txt file the IP is different from my home IP.
> 
> Also in the openvpn log I see it succesfully connects.
> But once it is connected to the vpn I cant access flood anymore.
> 
> What do I do?

i just clones the repo in a fresh directory to verify this issue and it's running on my end fine. how do you access the container?

**Comment by ThomasMcFarlane** [comment]
@h1f0x I have the same issue.

I forward the port 9000 from the host to 80 in the container - this is working fine without the VPN active but, as soon as it is active, floor no longer responds.
I suspect this is the case for VPNs that do not support port forwarding, or only support randomised port forwarding (Private Internet Access is the one I am using - this only supports randomised port forwarding on a few locations, most locations do not).
Is there a way around requiring port forwarding here by modifying the docker network config?

**Comment by MiguelNdeCarvalho** [comment]
Hey,
I am getting the same issue as you @ThomasMcFarlane , but I found a way by using `Traefik` to reverse proxy it. 
Thanks,
Miguel de Carvalho

**Comment by ThomasMcFarlane** [comment]
Please could you share this fix, @MiguelNdeCarvalho ?
I did have it working but the connection ceases fairly quickly and I end up with no downloads running through the sockets.
Suspect I missed something in the Traefik config.

**Comment by MiguelNdeCarvalho** [comment]
Somehow I was getting UDP tracker problem, I tried to open the ports but it didnt fix

**Comment by tuxfoo** [comment]
Yeah, I have this issue too.

When vpn is off, I can access it via http://ip-of-server:8000 but when vpn is running I cannot. Same results when I run nmap on port 8000.

If I configure a socks 5 proxy via ssh 
`ssh -D 1234 -q -C -N -f root@ip-of-server`
and then set Firefox to use it, I can access the web UI with the vpn running by going to http://172.17.0.2

So a reverse proxy should fix it, I think it might be possible to configure such a reverse proxy in nginx.
I will have a tinker in the weekend.

**Comment by tuxfoo** [comment]
I have apache also running on my server(not in a container), so I used that to set up the reverse proxy. 
I can now log into the webui with openvpn running.
  
Here is my configuration of the virtualhost.

```
ServerName seed.domainname.org
ErrorLog /var/log/virtualmin/seed.domainname.org_error_log
CustomLog /var/log/virtualmin/seed.domainname.org_access_log combined
DocumentRoot /home/seed/public_html

<Directory /home/seed/public_html>
Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
allow from all
AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
Require all granted
</Directory>
  
  # Encoded slashes need to be allowed
  AllowEncodedSlashes NoDecode

  # keep the host
  ProxyPreserveHost On

  ProxyPass /.well_known/ !
  
  ProxyPass           / http://127.0.0.1:8000/
  ProxyPassReverse    / http://127.0.0.1:8000/
```

**Comment by etymotic** [comment]
I'm having the same problem. My port is 8000->80. With no VPN connection, I can use Flood. Once the VPN is connected, I can't access flood through http://ip-address:8000 anymore.

I think it has to do with the "dev tun" config. Using "tap" instead should work better, but I have no idea how to set that up properly. https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/ talks a bit about it.

**Comment by tuxfoo** [comment]
> I'm having the same problem. My port is 8000->80. With no VPN connection, I can use Flood. Once the VPN is connected, I can't access flood through http://ip-address:8000 anymore.
> 
> I think it has to do with the "dev tun" config. Using "tap" instead should work better, but I have no idea how to set that up properly. https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/ talks a bit about it.

If you want to do it without a reverse proxy, you could also set up a second tun device, but you would also need to set a tunnel on the device on the network which you want to access the container from or just on the container host.

A  apache/nginx Reverse proxy is probably the better solution in most cases. You could also use apache/nginx to set up reverse proxies to other containers you might have, for example jellyfin/plex/emby. It also avoids the users having to add a port number to the end.

**Comment by etymotic** [comment]
> > I'm having the same problem. My port is 8000->80. With no VPN connection, I can use Flood. Once the VPN is connected, I can't access flood through http://ip-address:8000 anymore.
> > I think it has to do with the "dev tun" config. Using "tap" instead should work better, but I have no idea how to set that up properly. https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/ talks a bit about it.
> 
> If you want to do it without a reverse proxy, you could also set up a second tun device, but you would also need to set a tunnel on the device on the network which you want to access the container from or just on the container host.
> 
> A apache/nginx Reverse proxy is probably the better solution in most cases. You could also use apache/nginx to set up reverse proxies to other containers you might have, for example jellyfin/plex/emby. It also avoids the users having to add a port number to the end.

I have some learning to do about reverse proxies. I sort of get the general gist, but have no experience with it.

Is there any advantage to me learning how to set this up, and having my browser configured to go through the reverse proxy (would ALL of my browser traffic go through it?), vs. me learning how to make DockerContainer1 get it's internet connection from DockerContainer2?

For example, is it possible for me to set up an OpenVPN container and an rTorrent/Flood container, and have rTorrent/Flood look to OpenVPN for it's connection?

**Comment by tuxfoo** [comment]
> > > I'm having the same problem. My port is 8000->80. With no VPN connection, I can use Flood. Once the VPN is connected, I can't access flood through http://ip-address:8000 anymore.
> > > I think it has to do with the "dev tun" config. Using "tap" instead should work better, but I have no idea how to set that up properly. https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/ talks a bit about it.
> > 
> > 
> > If you want to do it without a reverse proxy, you could also set up a second tun device, but you would also need to set a tunnel on the device on the network which you want to access the container from or just on the container host.
> > A apache/nginx Reverse proxy is probably the better solution in most cases. You could also use apache/nginx to set up reverse proxies to other containers you might have, for example jellyfin/plex/emby. It also avoids the users having to add a port number to the end.
> 
> I have some learning to do about reverse proxies. I sort of get the general gist, but have no experience with it.
> 
> Is there any advantage to me learning how to set this up, and having my browser configured to go through the reverse proxy (would ALL of my browser traffic go through it?), vs. me learning how to make DockerContainer1 get it's internet connection from DockerContainer2?
> 
> For example, is it possible for me to set up an OpenVPN container and an rTorrent/Flood container, and have rTorrent/Flood look to OpenVPN for it's connection?

You wont need need to set up anything in your browser if you create a reverse proxy. Another advantage is you can use a domain name to access your containers, eg; plex.domainname.org, rutorrent.domainname.org, rutorrent.myhome.internal
You just set up a virtual host to each container and give it a domain name and point it to what ever port the container uses.

Learning how to make tunnels between containers like you mentioned is also very useful, the benefit of doing that way is that you can make any container you want go through the VPN.

**Comment by etymotic** [comment]
I have no idea how to set up nginx to do any of this. I know this isn't the best place to ask, but if anyone wants to point me in the right direction...

I don't have a domain name, and I'm not interested in getting one. How would I set up a reverse proxy on my LAN to point to my-lan-ip:8000?

**Comment by tuxfoo** [comment]
> I have no idea how to set up nginx to do any of this. I know this isn't the best place to ask, but if anyone wants to point me in the right direction...
> 
> I don't have a domain name, and I'm not interested in getting one. How would I set up a reverse proxy on my LAN to point to my-lan-ip:8000?

You do not need a public domain name, you can just use something like flood.home.internal providing that you have DNS set up correctly.

The jellyfin docs has a section explaining briefly how to set up reverse proxies to a container using a few different methods.
https://jellyfin.org/docs/general/administration/reverse-proxy.html

**Comment by f-sketch** [comment]
I encountered the same problem because my OpenVPN client config did not call the correct "up" and "down" scripts

Using this config everything works fine and flood is accessible:

`
client
dev tun0
proto tcp
remote 1.2.3.4 5678
resolv-retry infinite
ca /config/vpn/keys/ca.crt
cert /config/vpn/keys/123.crt
key /config/vpn/keys/123.key
cipher AES-128-CBC

script-security 2
up /usr/bin/up.sh
down /usr/bin/down.sh

log-append /config/vpn/openvpn.log
`

**Comment by f-sketch** [comment]
I fixed it like this.

**Warning**: This might leak your IP while torrenting if not done right. Check your torrent IP (using e.g. torguard.net) after doing this before downloading anything.

Make sure your OpenVPN "/config/vpn/client.conf" contains this:
```
script-security 2
up /usr/bin/up.sh
down /usr/bin/down.sh

#ignore pushed routes
route-noexec
```

Make sure your OpenVPN "/config/rtorrent/rtorrent.rc" contains this:
```
# Set an interface with IPv4 address to bind to: [eth0|tun0]
method.insert = cfg.interface.bind, string|const|private, (cat,"tun0")
# Get IPv4 address of a given interface
method.insert = get_interface_ipv4_address, simple|private, \
    "execute.capture=bash,-c,\"$cat=\\\"echo -n \$(ip -o -4 addr show \\\",$argument.0=,\\\" | grep -Po 'inet \\\\\\\\\\K[\\\\\\\\\\d.]+')\\\"\""
# The IP address the listening socket and outgoing connections is bound to. (bind)
schedule2 = set_bind_address, 0, 0, \
    "branch=((cfg.interface.bind)), \
        ((network.bind_address.set,(get_interface_ipv4_address,(cfg.interface.bind))))"
```

**Comment by Whisper40** [comment]
Please close this project. The problem above not solved on July 2020. 
I have needed to change a lot of things in the original conf to make it works, and when it's ok, ip is OK, but flood is killed, so hours for nothing..
Please close or solve the problem.

**Comment by MiguelNdeCarvalho** [comment]
Hey,
I am going to start working on this project from scratch.
Thanks,
Miguel de Carvalho

**Comment by Whisper40** [comment]
Hi ! Good to know, can you give us a link when you start it for following it ?

**Comment by MiguelNdeCarvalho** [comment]
I will send the link here @Whisper40

**Comment by Whisper40** [comment]
A solution that worked on my side is to create another nginx container, to create a reverse proxy to the flood container and to expose this nginx container. All working after this !
